[package]
name = "tauri-rfd"
version = "0.1.0"
edition = "2018"

authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
description = "Rusty File Dialog"
keywords = ["file","ui","dialog"]
license = "MIT"
repository = "https://github.com/PolyMeilex/rfd"
documentation = "https://docs.rs/rfd"

[lib]
name = "rfd"

[features]
default=["parent"]
parent=["raw-window-handle"]
file-handle-inner = []

[dev-dependencies]
futures="0.3.12"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
objc_id = "0.1.1"
dispatch = "0.2.0"
block="0.1.6"
objc-foundation = "0.1.1"


[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["winuser","combaseapi","objbase","shobjidl","shellapi"] }

[target.'cfg(target_os = "linux")'.dependencies]
gtk-sys = { version="0.14.0", features=["v3_20"] }
glib-sys = "0.14.0"
gobject-sys = "0.14.0"
lazy_static = "1.4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen= "0.2.69"
js-sys= "0.3.46"
web-sys={ version = "0.3.46", features = [
  'Document',
  'Element',
  'HtmlInputElement',
  'HtmlButtonElement',
  'Window',
  'File',
  'FileList',
  'FileReader',
] }
wasm-bindgen-futures = "0.4.19"


[[example]]
name = "simple"
[[example]]
name = "async"

[dependencies]
raw-window-handle = { version="0.3.3", optional=true }

[package.metadata.docs.rs]
all-features = true
